### ISSUE TITLE
[PDF Menu viewer] Need solution other than Scribd?

### ISSUE THREAD

**Issue by JenEllis44** [ample/kazeotr-com#10]
This would apply to PDF menu display on the [menus](https://kazeotr-com.netlify.com/menus.html)  page as well as on the [Happy Hour](https://kazeotr-com.netlify.com/happy-hour.html) page.
<img width="838" alt="Screen Shot 2019-04-09 at 1 37 59 PM" src="https://user-images.githubusercontent.com/30153638/55822284-4988ac00-5acd-11e9-97d1-e4824851e292.png">

**Comment by tcmacdonald** [comment]
Closed via ee5ae59
