### ISSUE TITLE
[Homepage] Video feature not displaying

### ISSUE THREAD

**Issue by JenEllis44** [ample/kazeotr-com#2]
On the homepage of the site there is a section that says, "CHECK OUT OUR VIDEO FEATURE ON CINCINNATI REFINED", but there is not a video displaying.
<img width="930" alt="Screen Shot 2019-04-09 at 12 48 48 PM" src="https://user-images.githubusercontent.com/30153638/55819335-8b622400-5ac6-11e9-8054-a4983a2132a5.png">

**Comment by tcmacdonald** [comment]
@JenEllis44 Can you work with the client to get this video uploaded to Youtube or Vimeo so we can just embed from there? Let me know. Thanks!
